### ISSUE TITLE
gvle-windows:   crash

### ISSUE THREAD

**Issue by helraynal** [vle-forge/vle#330] opened 2018-04-25 15:14 UTC
a gvle crash often occurs  when adding a 2nd output port on an atomic model.

**Comment by Chabrier** [comment] 2018-05-03 09:32
This does not seems to always occurs.
Could you tell which version and OS you are using.

And also do you have an idea on a favorable use case to reproduce the bug?

Thanks anyway.

**Comment by quesnel** [comment] 2019-01-14 11:56
Seems to be fix, closing now. Feel free to reopen if you still see some warnings.

**Closed by quesnel** 2019-01-14 11:56 UTC
Labels: bug, gvle
